name: "forward_billing_app"
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^3.9.0
  firebase_auth: ^5.3.4
  cloud_firestore: ^5.4.0
  firebase_messaging: ^15.1.3
  google_sign_in: ^6.1.10
  sqflite: ^2.3.0
  path: ^1.8.3
  synchronized: ^3.1.0
  math_expressions: ^2.4.0
  share_plus: ^11.0.0
  pdf: ^3.10.7
  path_provider: ^2.1.1
  printing: ^5.11.1
  barcode_widget: ^2.0.4
  flutter_bloc: ^8.1.3
  font_awesome_flutter: ^10.8.0
  carousel_slider: ^5.0.0
  animated_bottom_navigation_bar: ^1.2.0
  flutter_slidable: ^3.0.0
  intl: 0.20.2
  cached_network_image: ^3.4.1
  google_fonts: ^6.1.0
  flutter_contacts: ^1.1.9+2
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.2
  shimmer: ^3.0.0
  provider: ^6.1.0
  syncfusion_flutter_xlsio: ^30.1.41
  lucide_icons: ^0.257.0
  dropdown_button2: ^2.3.9
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.4
  package_info_plus: ^8.0.2
  image_picker: ^1.0.4
  sqflite_common_ffi: ^2.3.6
  flutter_svg: ^2.0.7
  lottie: ^3.1.0
  animations: ^2.0.11
  permission_handler: ^11.3.1
  flutter_local_notifications: ^17.2.2
  firebase_analytics: ^11.3.8
  timezone: ^0.9.4
  awesome_snackbar_content: ^0.1.3
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/progress.json
    - assets/loginanimation.json
    - assets/Authentication Lock Login.json
    - assets/Get started.json
    
