// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA_N-M2nrJs33mX-hzluF5ekwVe9P4iROw',
    appId: '1:946800454244:web:43b9d44ba3ec2ae281cd71',
    messagingSenderId: '946800454244',
    projectId: 'pos-app-68bcc',
    authDomain: 'pos-app-68bcc.firebaseapp.com',
    storageBucket: 'pos-app-68bcc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_N-M2nrJs33mX-hzluF5ekwVe9P4iROw',
    appId: '1:946800454244:android:43b9d44ba3ec2ae281cd71',
    messagingSenderId: '946800454244',
    projectId: 'pos-app-68bcc',
    storageBucket: 'pos-app-68bcc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_N-M2nrJs33mX-hzluF5ekwVe9P4iROw',
    appId: '1:946800454244:ios:43b9d44ba3ec2ae281cd71',
    messagingSenderId: '946800454244',
    projectId: 'pos-app-68bcc',
    storageBucket: 'pos-app-68bcc.firebasestorage.app',
    iosClientId:
        '946800454244-43b9d44ba3ec2ae281cd71.apps.googleusercontent.com',
    iosBundleId: 'com.example.forwardBillingApp',
  );
}
